### PR TITLE
Https and license

### LINKED ISSUE #44: The online demo is broken
image

### PR DESCRIPTION
**Pull request by IonicaBizau**
- Use `https` instead of `http`. Fixes #44. I avoided to use `//` since it will brake the local page.
- Renamed the `readme.md` file into `README.md`. Also, cleaned up the markdown and added a link to the license file.

---

I'm using this tool for the [Bloggify social plugin](http://bloggify.net/), which is open-source [here](https://github.com/Bloggify/social).

You can see it in action on [my website](http://ionicabizau.net/blog/21-we-re-getting-social). :smile:

### CODE REVIEW

**Comment by IonicaBizau** [comment]
I'm not sure how should I generate the `gh-pages` files... /cc @samccone @sethkrasnianski

**Comment by samccone** [comment]
no worries I will deploy that for you :)

**Comment by IonicaBizau** [comment]
:bulb:  *pro tip*: comment on the [<kbd>File changed</kbd>](https://github.com/mojotech/social-builder/pull/46/files) instead of commenting on my commits, because doing so when I will delete my fork they will disappear. Also, I have edit privileges on your comments on my commits (since I'm the fork owner). :sunglasses:

**Comment by samccone** [comment]
great testing locally

**Comment by samccone** [comment]
:clap: thanks so much

**Comment by IonicaBizau** [comment]
You're welcome! Seems it's already working on GitHub Pages, but not yet on mojotech.com. :+1:

**Comment by samccone** [comment]
yeah, so it looks like the images that we are inlining are messed up and defaulting to http still, I think it might end up being a JS fix as well

screen shot 2015-03-13 at 12 02 11 pm

so github is still throwing the issue, but since we are not in an iframe we are able to still see the page

**Pull request merged**
